### ISSUE TITLE
Consider to add "awesome" label to get more recognition

### ISSUE THREAD

**Issue by RusinovAnton** [miukimiu/data-visualization#1]
For instance, there is awesome list of awesome lists: https://github.com/sindresorhus/awesome

**Comment by elizabetdev** [comment]
Hi! 
Thanks for the suggestion. There's already one Data Viz list: https://github.com/fasouto/awesome-dataviz

I'm creating my own more for learning purposes. Let's see how the content grows, and I might add it to the awesome list.

Thanks!
